language: swift

osx_image: xcode8.3

xcode_sdk: iphonesimulator10.3

xcode_workspace: RCMVVMSample.xcworkspace

xcode_scheme: 
    - RCMVVMSampleLibTests
    - RCMVVMSampleViewTests

branches:
  only:
    - travis
